name: Deploy Firebase Function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  deploy_functions:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          # FIX: Use Node.js v18 to match the engine requirement in functions/package.json
          node-version: 18 

      - name: Install Function Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only functions --project ${{ secrets.GCP_PROJECT_ID }} --non-interactive
